const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILED: 'FETCH_COLLECTIONS_FAILED',
  SET_SEARCH_KEYWORD: 'SET_SEARCH_KEYWORD',
  CLEAR_SEARCH_KEYWORD: 'CLEAR_SEARCH_KEYWORD',
};

export default ShopActionTypes;
